import { Resend } from "resend";
import { saveLead } from "@/lib/leadStore";
import { SITE_URL } from "@/lib/siteMetadata";

export interface InquiryPayload {
  name: string;
  email: string;
  phone?: string;
  instagram?: string;
  message?: string;
  product: string;
  source: string;
  formType: string;
  extraFields?: Record<string, string>;
}

// ============================================================
// Canonical internal-recipient list — SINGLE SOURCE OF TRUTH.
//
// Every RootFlute-team-facing notification generated by the website (a new
// inquiry, a completed sale, a made-to-order deposit, etc.) must reach BOTH
// of these permanent mailboxes. This list is a FLOOR, not a ceiling:
// additional recipients configured via INTERNAL_SALE_NOTIFICATION_EMAILS
// (see parseInternalNotificationRecipients, below) are merged on top of it,
// never in place of it, so a missing or misconfigured env var can never drop
// delivery below these two addresses. Every internal-send call site in this
// file goes through `getInternalRecipients()` — none builds its own `to`
// list — which is what makes it structurally impossible for a future
// internal pathway to accidentally notify only one of the two.
const REQUIRED_INTERNAL_RECIPIENTS = ["danraasch1@gmail.com", "rootflute@gmail.com"];

function getInternalRecipients(): string[] {
  return [...new Set([...REQUIRED_INTERNAL_RECIPIENTS, ...parseInternalNotificationRecipients()])];
}

function formatTimestamp(): string {
  return new Date().toLocaleString("en-US", {
    timeZone: "America/New_York",
    dateStyle: "full",
    timeStyle: "short",
  });
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function buildEmailHtml(payload: InquiryPayload, timestamp: string): string {
  const rows: [string, string][] = [
    ["Product / Item", payload.product || "—"],
    ["Full Name", payload.name],
    ["Email", payload.email],
    ["Phone", payload.phone || "—"],
    ["Instagram", payload.instagram ? `@${payload.instagram.replace(/^@/, "")}` : "—"],
    ...(payload.extraFields ? (Object.entries(payload.extraFields) as [string, string][]) : []),
    ["Source", payload.source],
    ["Submitted", timestamp],
  ];

  const rowsHtml = rows
    .map(
      ([label, value]) => `
      <tr>
        <td style="padding:8px 16px 8px 0;color:#9a8a6a;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;white-space:nowrap;vertical-align:top;font-family:Arial,sans-serif;">${esc(label)}</td>
        <td style="padding:8px 0;color:#e8e0d0;font-size:14px;vertical-align:top;font-family:Georgia,serif;">${esc(value)}</td>
      </tr>`
    )
    .join("");

  const messageBlock = payload.message?.trim()
    ? `
    <tr>
      <td colspan="2" style="padding:20px 0 0;">
        <p style="margin:0 0 8px;color:#9a8a6a;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;font-family:Arial,sans-serif;">Message</p>
        <p style="margin:0;color:#e8e0d0;font-size:14px;line-height:1.7;white-space:pre-wrap;font-family:Georgia,serif;">${esc(payload.message.trim())}</p>
      </td>
    </tr>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#0d0d0b;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#0d0d0b;padding:40px 20px;">
    <tr><td align="center">
      <table width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:580px;background:#141410;border:1px solid #2a2820;">
        <tr><td style="height:2px;background:linear-gradient(90deg,transparent,#c8a45a,transparent);font-size:0;">&nbsp;</td></tr>
        <tr>
          <td style="padding:32px 32px 24px;border-bottom:1px solid #2a2820;">
            <p style="margin:0 0 10px;color:#c8a45a;font-size:10px;text-transform:uppercase;letter-spacing:0.3em;font-family:Arial,sans-serif;">${esc(payload.formType)}</p>
            <p style="margin:0;color:#e8e0d0;font-size:22px;font-weight:300;font-family:Georgia,serif;">${esc(payload.name)}</p>
            <p style="margin:6px 0 0;color:#6b6356;font-size:12px;font-family:Arial,sans-serif;">${esc(payload.email)}</p>
          </td>
        </tr>
        <tr>
          <td style="padding:24px 32px;">
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
              ${rowsHtml}
              ${messageBlock}
            </table>
          </td>
        </tr>
        <tr>
          <td style="padding:20px 32px 28px;border-top:1px solid #2a2820;">
            <p style="margin:0;color:#4a4336;font-size:11px;font-family:Arial,sans-serif;">
              Sent from the RootFlute ${esc(payload.formType.toLowerCase())} form
              &nbsp;&middot;&nbsp;
              <a href="https://${esc(payload.source)}" style="color:#c8a45a;text-decoration:none;">${esc(payload.source)}</a>
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function buildEmailText(payload: InquiryPayload, timestamp: string): string {
  const lines = [
    `${payload.formType} — ${payload.source}`,
    ``,
    `Product:    ${payload.product || "—"}`,
    ``,
    `Name:       ${payload.name}`,
    `Email:      ${payload.email}`,
    `Phone:      ${payload.phone || "—"}`,
    `Instagram:  ${payload.instagram || "—"}`,
  ];

  if (payload.extraFields) {
    for (const [k, v] of Object.entries(payload.extraFields)) {
      lines.push(`${k.padEnd(11)} ${v}`);
    }
  }

  lines.push(
    ``,
    `Message:`,
    payload.message?.trim() || "(no message provided)",
    ``,
    `Source:     ${payload.source}`,
    `Submitted:  ${timestamp}`,
    ``,
    `—`,
    `Sent from the RootFlute acquisition form.`
  );

  return lines.join("\n");
}

// Persists a durable backup of the lead regardless of email outcome — a
// Resend outage or misconfiguration must never mean the lead is simply gone.
// Wrapped so a Blob failure here can never mask or block the caller's actual
// email result.
async function backupLead(payload: InquiryPayload, emailDelivered: boolean): Promise<void> {
  try {
    await saveLead({
      formType: payload.formType,
      product: payload.product,
      name: payload.name,
      email: payload.email,
      phone: payload.phone ?? "",
      instagram: payload.instagram ?? "",
      message: payload.message ?? "",
      source: payload.source,
      extraFields: payload.extraFields ?? null,
      emailDelivered,
    });
  } catch (err) {
    console.error(`[inquiry] Failed to save durable lead backup:`, err);
  }
}

export async function sendInquiryEmail(payload: InquiryPayload): Promise<{ ok: boolean; reason?: string }> {
  const timestamp = formatTimestamp();

  if (!process.env.RESEND_API_KEY) {
    console.error(`[inquiry] RESEND_API_KEY is not set — email NOT sent. Add it to Vercel env vars.`);
    console.info(`[inquiry] Captured payload:`, JSON.stringify({ ...payload, timestamp }));
    await backupLead(payload, false);
    return { ok: false, reason: "no_api_key" };
  }

  // Requires RESEND_FROM_EMAIL (a verified-domain sender), same as the other
  // two internal/customer sends in this file and for the same reason: the
  // shared onboarding@resend.dev sandbox sender can only deliver to the
  // Resend account owner's own address, so it would silently drop one of the
  // two required internal recipients rather than failing loudly. This lead is
  // still backed up (see backupLead below) even when the email can't send.
  const from = process.env.RESEND_FROM_EMAIL;
  if (!from) {
    console.error(
      `[inquiry] RESEND_FROM_EMAIL is not set — refusing to send from the shared sandbox sender, which cannot reliably reach both required internal recipients. Configure a verified Resend domain.`
    );
    console.info(`[inquiry] Captured payload:`, JSON.stringify({ ...payload, timestamp }));
    await backupLead(payload, false);
    return { ok: false, reason: "no_verified_sender" };
  }

  const recipients = getInternalRecipients();
  console.info(`[inquiry] Sending email — from: ${from} to: ${recipients.join(", ")} form: ${payload.formType}`);

  const resend = new Resend(process.env.RESEND_API_KEY);

  const { data, error } = await resend.emails.send({
    from,
    to: recipients,
    replyTo: payload.email,
    subject: `${payload.formType} — ${payload.product || "General"}`,
    html: buildEmailHtml(payload, timestamp),
    text: buildEmailText(payload, timestamp),
  });

  if (error) {
    console.error(`[inquiry] Resend rejected the send:`, JSON.stringify(error));
    console.info(`[inquiry] Payload that failed:`, JSON.stringify({ ...payload, timestamp }));
    await backupLead(payload, false);
    return { ok: false, reason: "resend_error" };
  }

  console.info(`[inquiry] Email sent successfully. Resend id: ${data?.id}`);
  await backupLead(payload, true);
  return { ok: true };
}

// ============================================================
// Post-purchase customer confirmation email.
//
// A dedicated, customer-facing message — NOT the internal inquiry body.
// Sent by the checkout webhook after a sale is authoritative. Delivery is
// best-effort: a failure here never affects the completed sale, and the
// caller records send-state in the durable order store for safe retries.
//
// Requires RESEND_FROM_EMAIL (a verified-domain sender). The shared
// onboarding@resend.dev fallback used for internal mail cannot reliably
// deliver to arbitrary customer addresses, so this function refuses to send
// from it and reports the reason instead of silently failing.
// ============================================================

export interface PurchaseConfirmationPayload {
  to: string;
  customerName: string | null;
  itemName: string;
  itemCategoryLabel: string;
  /** Human-readable amount already formatted, e.g. "$1.00". */
  amountFormatted: string;
  /** Short, human-quotable reference derived from the Stripe session id. */
  orderReference: string;
  /** One-line "Name, address" summary, or null if no shipping was collected. */
  shippingSummary: string | null;
  /** Stable idempotency key (per Stripe session) passed through to Resend. */
  idempotencyKey: string;
  /**
   * A permanent made-to-order design was ordered (not a finite one-of-one
   * piece). Switches the wording only — the finite email is left exactly as
   * it always was. Absent/false === finite.
   */
  madeToOrder?: boolean;
  /**
   * Present ONLY for a made-to-order order paid as a 50% deposit. Switches the
   * wording to deposit terms; absent === the certified full-payment email,
   * unchanged. Amounts are pre-formatted by the caller from the durable order
   * record. Shipping is never given an amount — it is simply still due.
   */
  deposit?: DepositSummary;
}

/** Pre-formatted amounts for a made-to-order 50% deposit order. */
export interface DepositSummary {
  fullPriceFormatted: string;
  paidFormatted: string;
  balanceFormatted: string;
}

const SUPPORT_URL = `${SITE_URL}/acquisition-support`;

// Deposit wording. Never calls the deposit full payment, never gives a
// shipping amount, delivery date or completion date.
const DEPOSIT_BODY =
  "Your 50% deposit has been received and your made-to-order order is in. This is a deposit, not full payment: the remaining 50% balance, plus shipping, is due before your instrument ships. Daniel will personally follow up regarding the creation of your instrument and the next steps — please watch the inbox for the email address you used at checkout.";

// The branded sender (RESEND_FROM_EMAIL, e.g. acquisitions@rootflute.com) is
// not an operational mailbox — Daniel's actual inbox is RootFlute@gmail.com.
// Replies to the customer confirmation email must land there.
const PURCHASE_REPLY_TO_EMAIL = "RootFlute@gmail.com";

function buildPurchaseConfirmationHtml(p: PurchaseConfirmationPayload): string {
  const greeting = p.customerName ? `${esc(p.customerName)},` : "Thank you.";
  const mto = p.madeToOrder === true;
  const dep = mto ? p.deposit : undefined;
  const rows: [string, string][] = [
    [mto ? "Instrument" : "Piece", `${esc(p.itemName)}`],
    ["Category", esc(p.itemCategoryLabel)],
    ...(dep
      ? ([
          ["Full Price", esc(dep.fullPriceFormatted)],
          ["Deposit Paid (50%)", esc(dep.paidFormatted)],
          ["Remaining Balance (50%)", esc(dep.balanceFormatted)],
          ["Shipping", "Additional &mdash; due before shipment"],
        ] as [string, string][])
      : ([["Amount", esc(p.amountFormatted)]] as [string, string][])),
    ["Order Reference", esc(p.orderReference)],
    ...(p.shippingSummary ? ([["Ship To", esc(p.shippingSummary)]] as [string, string][]) : []),
  ];

  const rowsHtml = rows
    .map(
      ([label, value]) => `
      <tr>
        <td style="padding:8px 16px 8px 0;color:#9a8a6a;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;white-space:nowrap;vertical-align:top;font-family:Arial,sans-serif;">${label}</td>
        <td style="padding:8px 0;color:#e8e0d0;font-size:14px;vertical-align:top;font-family:Georgia,serif;">${value}</td>
      </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#0d0d0b;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#0d0d0b;padding:40px 20px;">
    <tr><td align="center">
      <table width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:580px;background:#141410;border:1px solid #2a2820;">
        <tr><td style="height:2px;background:linear-gradient(90deg,transparent,#c8a45a,transparent);font-size:0;">&nbsp;</td></tr>
        <tr>
          <td style="padding:36px 32px 20px;">
            <p style="margin:0 0 12px;color:#c8a45a;font-size:10px;text-transform:uppercase;letter-spacing:0.3em;font-family:Arial,sans-serif;">${dep ? "Deposit Received" : mto ? "Order Confirmed" : "Acquisition Confirmed"}</p>
            <p style="margin:0 0 6px;color:#e8e0d0;font-size:24px;font-weight:300;font-family:Georgia,serif;">${dep ? "Your instrument order has been received." : mto ? "Your instrument has been ordered." : "Your piece has been claimed."}</p>
            <p style="margin:0;color:#8a8170;font-size:13px;font-family:Georgia,serif;">${greeting}</p>
          </td>
        </tr>
        <tr>
          <td style="padding:8px 32px 20px;">
            <p style="margin:0;color:#b8ae98;font-size:14px;line-height:1.7;font-family:Georgia,serif;">
              ${
                dep
                  ? DEPOSIT_BODY
                  : mto
                  ? `Your checkout completed and your made-to-order instrument has been ordered. Daniel
              will personally follow up regarding the creation of your instrument and the next
              steps &mdash; please watch the inbox for the email address you used at checkout.`
                  : `Your checkout completed and this one-of-one piece is now reserved to you. Daniel
              will personally follow up regarding your acquisition and the next steps &mdash;
              please watch the inbox for the email address you used at checkout.`
              }
            </p>
          </td>
        </tr>
        <tr>
          <td style="padding:4px 32px 24px;">
            <table width="100%" cellpadding="0" cellspacing="0" border="0" style="border-top:1px solid #2a2820;">
              <tr><td style="height:16px;font-size:0;">&nbsp;</td></tr>
              ${rowsHtml}
            </table>
          </td>
        </tr>
        <tr>
          <td style="padding:8px 32px 32px;border-top:1px solid #2a2820;">
            <p style="margin:16px 0 12px;color:#9a8a6a;font-size:12px;font-family:Arial,sans-serif;">${mto ? "Need help with your order?" : "Need help with your acquisition?"}</p>
            <a href="${SUPPORT_URL}" style="display:inline-block;padding:12px 22px;background:#c8a45a;color:#141410;font-size:13px;font-weight:bold;text-decoration:none;font-family:Arial,sans-serif;letter-spacing:0.04em;">${mto ? "Request support" : "Request support or a return"} &rarr;</a>
            <p style="margin:14px 0 0;color:#6b6356;font-size:11px;line-height:1.6;font-family:Arial,sans-serif;">
              Daniel personally reviews each request and follows up with you directly.
            </p>
          </td>
        </tr>
        <tr>
          <td style="padding:18px 32px 26px;border-top:1px solid #2a2820;">
            <p style="margin:0;color:#4a4336;font-size:11px;font-family:Arial,sans-serif;">
              RootFlute &nbsp;&middot;&nbsp;
              <a href="${SITE_URL}" style="color:#c8a45a;text-decoration:none;">www.rootflute.com</a>
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function buildPurchaseConfirmationText(p: PurchaseConfirmationPayload): string {
  const mto = p.madeToOrder === true;
  const dep = mto ? p.deposit : undefined;
  const lines = [
    dep
      ? `DEPOSIT RECEIVED — Your instrument order has been received.`
      : mto
      ? `ORDER CONFIRMED — Your instrument has been ordered.`
      : `ACQUISITION CONFIRMED — Your piece has been claimed.`,
    ``,
    p.customerName ? `${p.customerName},` : `Thank you.`,
    ``,
    ...(dep
      ? [DEPOSIT_BODY]
      : mto
      ? [
          `Your checkout completed and your made-to-order instrument has been ordered.`,
          `Daniel will personally follow up regarding the creation of your instrument`,
          `and the next steps — please watch the inbox for the email address you used`,
          `at checkout.`,
        ]
      : [
          `Your checkout completed and this one-of-one piece is now reserved to you.`,
          `Daniel will personally follow up regarding your acquisition and the next`,
          `steps — please watch the inbox for the email address you used at checkout.`,
        ]),
    ``,
    `${mto ? "Instrument:       " : "Piece:            "}${p.itemName}`,
    `Category:         ${p.itemCategoryLabel}`,
    ...(dep
      ? [
          `Full Price:       ${dep.fullPriceFormatted}`,
          `Deposit Paid:     ${dep.paidFormatted} (50%)`,
          `Remaining:        ${dep.balanceFormatted} (50%)`,
          `Shipping:         Additional — due before shipment`,
        ]
      : [`Amount:           ${p.amountFormatted}`]),
    `Order Reference:  ${p.orderReference}`,
  ];
  if (p.shippingSummary) lines.push(`Ship To:          ${p.shippingSummary}`);
  lines.push(
    ``,
    mto ? `Need help with your order? Request support:` : `Need help with your acquisition? Request support or a return:`,
    SUPPORT_URL,
    ``,
    `Daniel personally reviews each request and follows up with you directly.`,
    ``,
    `—`,
    `RootFlute · www.rootflute.com`
  );
  return lines.join("\n");
}

export async function sendPurchaseConfirmationEmail(
  payload: PurchaseConfirmationPayload
): Promise<{ ok: boolean; reason?: string }> {
  if (!process.env.RESEND_API_KEY) {
    console.error(`[purchase-confirmation] RESEND_API_KEY is not set — email NOT sent.`);
    return { ok: false, reason: "no_api_key" };
  }

  const from = process.env.RESEND_FROM_EMAIL;
  if (!from) {
    console.error(
      `[purchase-confirmation] RESEND_FROM_EMAIL is not set — refusing to send a customer email from the shared sandbox sender. Configure a verified Resend domain and set RESEND_FROM_EMAIL. Order reference: ${payload.orderReference}`
    );
    return { ok: false, reason: "no_verified_sender" };
  }

  if (!payload.to) {
    console.error(
      `[purchase-confirmation] No customer email on the checkout session — cannot send. Order reference: ${payload.orderReference}`
    );
    return { ok: false, reason: "no_recipient" };
  }

  console.info(
    `[purchase-confirmation] Sending — from: ${from} to: ${payload.to} ref: ${payload.orderReference}`
  );

  const resend = new Resend(process.env.RESEND_API_KEY);

  const { data, error } = await resend.emails.send(
    {
      from,
      to: payload.to,
      replyTo: PURCHASE_REPLY_TO_EMAIL,
      subject: `Your RootFlute ${
        payload.madeToOrder === true ? (payload.deposit ? "order (50% deposit)" : "order") : "acquisition"
      } — ${payload.itemName}`,
      html: buildPurchaseConfirmationHtml(payload),
      text: buildPurchaseConfirmationText(payload),
    },
    { idempotencyKey: payload.idempotencyKey }
  );

  if (error) {
    console.error(`[purchase-confirmation] Resend rejected the send:`, JSON.stringify(error));
    return { ok: false, reason: "resend_error" };
  }

  console.info(`[purchase-confirmation] Sent. Resend id: ${data?.id}`);
  return { ok: true };
}

// ============================================================
// Internal merchant sale notification.
//
// A dedicated, operator-facing message — distinct from both the inquiry-form
// notification (sendInquiryEmail, pre-purchase leads) and the customer
// acquisition confirmation (sendPurchaseConfirmationEmail, post-purchase).
// Sent by the checkout webhook after a sale is authoritative. Delivery is
// best-effort and fully independent of the customer confirmation: a failure
// here never affects the completed sale, never affects inventory state, and
// never blocks or duplicates the customer email. The caller records
// send-state in its own durable order-store field (`internalNotificationSent`)
// so retries are safe and independent of the customer-confirmation flag.
//
// Recipients always include both permanent RootFlute addresses (see
// getInternalRecipients / REQUIRED_INTERNAL_RECIPIENTS, near the top of this
// file) — extra operational recipients can still be layered on via
// INTERNAL_SALE_NOTIFICATION_EMAILS (comma-separated) without a code deploy,
// but the two required mailboxes can never be configured away.
//
// Requires RESEND_FROM_EMAIL (a verified-domain sender), same as the
// customer confirmation and for the same reason: the shared onboarding@
// resend.dev sandbox sender can only deliver to the Resend account owner's
// own address, so it silently cannot reach a multi-recipient internal list
// (confirmed by a live test send during implementation). This function
// refuses to send from it and reports the reason instead of a delivery that
// partially or fully fails.
// ============================================================

export interface InternalSaleNotificationPayload {
  itemName: string;
  itemCategoryLabel: string;
  /** Human-readable amount already formatted, e.g. "$1,050.00". */
  amountFormatted: string;
  /** Short, human-quotable reference derived from the Stripe session id. */
  orderReference: string;
  stripeCheckoutSessionId: string;
  /** ISO timestamp of the sale (Order.soldAt). */
  purchaseTimestamp: string;
  customerName: string | null;
  customerEmail: string | null;
  customerPhone: string | null;
  shippingName: string | null;
  shippingAddress: string | null;
  /** Stable idempotency key (per Stripe session) passed through to Resend. */
  idempotencyKey: string;
  /** A permanent made-to-order design was ordered (the design stays live). */
  madeToOrder?: boolean;
  /** Present ONLY for a made-to-order 50% deposit order (see PurchaseConfirmationPayload.deposit). */
  deposit?: DepositSummary;
}

const EMAIL_ADDRESS_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// Parses INTERNAL_SALE_NOTIFICATION_EMAILS: comma-separated, trims
// whitespace, discards empty entries, drops anything that doesn't look like
// an email address (rather than letting a typo silently become a broken
// recipient array), and de-duplicates. Never throws — an absent or fully
// invalid value simply yields an empty list, which the caller treats as a
// configuration failure rather than sending to zero recipients silently.
function parseInternalNotificationRecipients(): string[] {
  const raw = process.env.INTERNAL_SALE_NOTIFICATION_EMAILS;
  if (!raw) return [];

  const seen = new Set<string>();
  for (const candidate of raw.split(",")) {
    const trimmed = candidate.trim();
    if (trimmed && EMAIL_ADDRESS_RE.test(trimmed)) {
      seen.add(trimmed);
    }
  }
  return [...seen];
}

function formatOrderTimestamp(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso;
  return date.toLocaleString("en-US", {
    timeZone: "America/New_York",
    dateStyle: "full",
    timeStyle: "short",
  });
}

function buildInternalSaleNotificationHtml(p: InternalSaleNotificationPayload): string {
  const dep = p.madeToOrder === true ? p.deposit : undefined;
  const rows: [string, string][] = [
    ["Piece", esc(p.itemName)],
    ["Category", esc(p.itemCategoryLabel)],
    ...(dep
      ? ([
          ["Payment", "MADE-TO-ORDER DEPOSIT (50%)"],
          ["Full Price", esc(dep.fullPriceFormatted)],
          ["Deposit Paid", esc(dep.paidFormatted)],
          ["Remaining Balance", esc(dep.balanceFormatted)],
          ["Shipping", "Still due before shipment (not charged)"],
        ] as [string, string][])
      : ([["Amount Paid", esc(p.amountFormatted)]] as [string, string][])),
    ["Customer Name", esc(p.customerName || "—")],
    ["Customer Email", esc(p.customerEmail || "—")],
    ["Customer Phone", esc(p.customerPhone || "—")],
    ["Ship To Name", esc(p.shippingName || "—")],
    ["Shipping Address", esc(p.shippingAddress || "—")],
    ["Order Reference", esc(p.orderReference)],
    ["Stripe Checkout Session", esc(p.stripeCheckoutSessionId)],
    ["Purchase Time", esc(formatOrderTimestamp(p.purchaseTimestamp))],
  ];

  const rowsHtml = rows
    .map(
      ([label, value]) => `
      <tr>
        <td style="padding:8px 16px 8px 0;color:#9a8a6a;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;white-space:nowrap;vertical-align:top;font-family:Arial,sans-serif;">${label}</td>
        <td style="padding:8px 0;color:#e8e0d0;font-size:14px;vertical-align:top;font-family:Georgia,serif;">${value}</td>
      </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#0d0d0b;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#0d0d0b;padding:40px 20px;">
    <tr><td align="center">
      <table width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:580px;background:#141410;border:1px solid #2a2820;">
        <tr><td style="height:2px;background:linear-gradient(90deg,transparent,#c8a45a,transparent);font-size:0;">&nbsp;</td></tr>
        <tr>
          <td style="padding:32px 32px 20px;">
            <p style="margin:0 0 10px;color:#c8a45a;font-size:10px;text-transform:uppercase;letter-spacing:0.3em;font-family:Arial,sans-serif;">Internal &middot; Sale Notification</p>
            <p style="margin:0;color:#e8e0d0;font-size:22px;font-weight:300;font-family:Georgia,serif;">${dep ? "MADE-TO-ORDER DEPOSIT" : "SALE CONFIRMED"}</p>
            <p style="margin:6px 0 0;color:#8a8170;font-size:13px;font-family:Georgia,serif;">${dep ? "A 50% deposit was paid on a made-to-order piece. The remaining balance and shipping must be collected before it ships. The design remains live for future orders." : p.madeToOrder === true ? "A made-to-order Root Flute instrument has been ordered. The design remains live for future orders." : "A Root Flute piece has been acquired."}</p>
          </td>
        </tr>
        <tr>
          <td style="padding:8px 32px 24px;">
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
              ${rowsHtml}
            </table>
          </td>
        </tr>
        <tr>
          <td style="padding:16px 32px 26px;border-top:1px solid #2a2820;">
            <p style="margin:0;color:#4a4336;font-size:11px;font-family:Arial,sans-serif;">
              Internal operational notification &middot; RootFlute &middot; do not forward to the customer.
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function buildInternalSaleNotificationText(p: InternalSaleNotificationPayload): string {
  const dep = p.madeToOrder === true ? p.deposit : undefined;
  const lines = [
    dep
      ? `MADE-TO-ORDER DEPOSIT — A 50% deposit was paid on a made-to-order piece. The remaining balance and shipping must be collected before it ships. The design remains live for future orders.`
      : p.madeToOrder === true
      ? `SALE CONFIRMED — A made-to-order Root Flute instrument has been ordered. The design remains live for future orders.`
      : `SALE CONFIRMED — A Root Flute piece has been acquired.`,
    ``,
    `Piece:              ${p.itemName}`,
    `Category:           ${p.itemCategoryLabel}`,
    ...(dep
      ? [
          `Payment:            MADE-TO-ORDER DEPOSIT (50%)`,
          `Full Price:         ${dep.fullPriceFormatted}`,
          `Deposit Paid:       ${dep.paidFormatted}`,
          `Remaining Balance:  ${dep.balanceFormatted}`,
          `Shipping:           Still due before shipment (not charged)`,
        ]
      : [`Amount Paid:        ${p.amountFormatted}`]),
    `Customer Name:      ${p.customerName || "—"}`,
    `Customer Email:     ${p.customerEmail || "—"}`,
    `Customer Phone:     ${p.customerPhone || "—"}`,
    `Ship To Name:       ${p.shippingName || "—"}`,
    `Shipping Address:   ${p.shippingAddress || "—"}`,
    `Order Reference:    ${p.orderReference}`,
    `Stripe Session:     ${p.stripeCheckoutSessionId}`,
    `Purchase Time:      ${formatOrderTimestamp(p.purchaseTimestamp)}`,
    ``,
    `—`,
    `Internal operational notification · RootFlute · do not forward to the customer.`,
  ];
  return lines.join("\n");
}

export async function sendInternalSaleNotificationEmail(
  payload: InternalSaleNotificationPayload
): Promise<{ ok: boolean; reason?: string }> {
  if (!process.env.RESEND_API_KEY) {
    console.error(
      `[internal-sale-notification] RESEND_API_KEY is not set — email NOT sent. ref: ${payload.orderReference}`
    );
    return { ok: false, reason: "no_api_key" };
  }

  const from = process.env.RESEND_FROM_EMAIL;
  if (!from) {
    console.error(
      `[internal-sale-notification] RESEND_FROM_EMAIL is not set — refusing to send from the shared sandbox sender, which cannot deliver to a multi-recipient internal list. Configure a verified Resend domain. ref: ${payload.orderReference}`
    );
    return { ok: false, reason: "no_verified_sender" };
  }

  // Always includes both required RootFlute addresses (see
  // getInternalRecipients) plus anything extra configured via
  // INTERNAL_SALE_NOTIFICATION_EMAILS — so this list can never be empty and
  // can never fall short of the two permanent mailboxes.
  const recipients = getInternalRecipients();

  console.info(
    `[internal-sale-notification] Sending — from: ${from} recipients: ${recipients.length} ref: ${payload.orderReference} session: ${payload.stripeCheckoutSessionId}`
  );

  const resend = new Resend(process.env.RESEND_API_KEY);

  const { data, error } = await resend.emails.send(
    {
      from,
      to: recipients,
      subject:
        payload.madeToOrder === true && payload.deposit
          ? `Root Flute MADE-TO-ORDER DEPOSIT — ${payload.itemName} — ${payload.deposit.paidFormatted} of ${payload.deposit.fullPriceFormatted}`
          : `Root Flute Sale — ${payload.itemName} — ${payload.amountFormatted}`,
      html: buildInternalSaleNotificationHtml(payload),
      text: buildInternalSaleNotificationText(payload),
    },
    { idempotencyKey: payload.idempotencyKey }
  );

  if (error) {
    console.error(
      `[internal-sale-notification] Resend rejected the send: ${JSON.stringify(error)} ref: ${payload.orderReference}`
    );
    return { ok: false, reason: "resend_error" };
  }

  console.info(`[internal-sale-notification] Sent. Resend id: ${data?.id} ref: ${payload.orderReference}`);
  return { ok: true };
}
